### ISSUE TITLE
Ruby 2.7 deprecation warning

### ISSUE THREAD

**Issue by NDuggan** [KimNorgaard/validates_hostname#14]
Version: 1.0.10
Ruby: 2.7.1

```sh
/usr/local/bundle/gems/validates_hostname-1.0.10/lib/validates_hostname.rb:245: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
```

**Comment by nadnoslen** [comment]
Hey @KimNorgaard & @NDuggan,

Pull this down and splatted the last argument of the `I18n.t(...)` calls to overcome this Ruby-2.7 warning.

Followed the direction of: https://bloggie.io/@kinopyo/how-to-fix-ruby-2-7-warning-using-the-last-argument-as-keyword-parameters-is-deprecated

Thanks.

**Comment by KimNorgaard** [comment]
Thanks for the PR. It's merged and pushed.
