### ISSUE TITLE
1.0.13 tag is pointing to an older commit with version1.0.12

### ISSUE THREAD

**Issue by pravi** [KimNorgaard/validates_hostname#19]
![image](https://github.com/KimNorgaard/validates_hostname/assets/708222/6729056b-f1f1-49b5-92fc-7ac8e7bcd33c)

This commit is just before you updated the gemspec file and version.rb

![image](https://github.com/KimNorgaard/validates_hostname/assets/708222/6530f714-90e5-4b0c-8b59-f7d78842fd12)

Please update the tag to point to the latest commit with correct version.

**Comment by KimNorgaard** [comment]
fixed, thanks for telling me
